name: CD

on:
  schedule:
    - cron: '0 * * * *' # run every hour
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 18.x

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERCEL_PAGES_DEPLOY_HOOK: ${{ secrets.VERCEL_PAGES_DEPLOY_HOOK }}

    steps:
      - name: Trigger Vercel Pages build
        if: startsWith(env.VERCEL_PAGES_DEPLOY_HOOK, 'https://api.vercel.com/v1/integrations/deploy/') && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
        run: curl -X POST ${{ secrets.VERCEL_PAGES_DEPLOY_HOOK }}
